### ISSUE TITLE
telephone entry field

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#36]
Got the following error message:

![image](https://user-images.githubusercontent.com/44071147/48580841-2986ff00-e918-11e8-9a60-8b656f3916a8.png)

I had entered :

![image](https://user-images.githubusercontent.com/44071147/48580892-4c191800-e918-11e8-9f2a-1506aa924247.png)

**Comment by jonodennis1** [comment]
has to have +44 in the front.....we probably just need to change the description.....

**Comment by jonodennis1** [comment]
separate issue : regarding world domination....can it cope with overseas mobiles?

**Comment by juur** [comment]
Correct - it requires a well-formed number. What I can do is tidy it up a bit (remove spaces, swap a leading 0 for +44 maybe). Let me see if the phone number checking library is 'clever' at converting.

Yes, currently it just checks the phone number is the same country as you are. Twilio (the SMS verification service that has been tested but is turned off due to £££) works in most countries.

**Comment by juur** [comment]
I've made this a little more robust - it removes 'obvious crap' such as blanks before submitting into the system.
